spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:15432/timedeposit
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=ALWAYS
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
